### ISSUE TITLE
Update to use wgtunnel release assets for OSX, Windows, and Linux (Arm64+Amd64)

### ISSUE THREAD

**Issue by hh** [cloudnative-coop/iimatey#1]
```
As a human
I want to share my terminal with a friend
In order to not do it alone

Given any common OS and ARCH
When I run iimatey
Then wgtunnel/tunnel client is downloaded from release assets
```

See https://github.com/cloudnative-coop/wgtunnel/issues/2

**Comment by hh** [comment]
@zachmandeville can you update the iimatey script and directions (repo and on the website) to use the new assets?

**Comment by zachmandeville** [comment]
Looked into this today and it is requiring some more delicate refactoring to fully use this fork.  We'd want to build assets for this new fork, but also update the packages to not reference coder anywhere.  The reason is that our iimatey script uses go to install wgtunnel and incorporate it into the flow, which means our go package needs to be up-to-date on this repo, and that package is being built using coder tools in more than one place.  We are also failing builds and tests because the ci is using some coder infrastructure, I think, or at least tools that are referencing coder and having some version/name errors.  

For the best maintainability, we would ideally keep the iimatey script as is, but do a `go install github.com/cloudnative-coop/wgtunnel@version` instead of `go install github.com/coder/wgtunnel@1.5.0`.  This will require some work to make sure to update all references and still get it to build.

**Comment by hh** [comment]
> The reason is that our iimatey script uses go to install wgtunnel and incorporate it into the flow.

The purpose of this issue is to ensure we don't need to install go, just download the three binaries:
- tmux
- ttyd
- tunnel (just the client)

Ideally folks just use artifacts already generated. I used a similar flow from iimateys compile steps to compile wgtunnel source and generate binaries.

For the matrix of outputs below I did the following:
```
GOOS=darwin GOARCH=arm64 make build 
mv build build-darwin-arm64
```

```
GOOS=windows GOARCH=amd64 make build
mv build build-windows-amd64
```

```
GOOS=linux GOARCH=arm GOARM=7 make build
mv build build-linux-armv7
```

```
$ file build-*/* | sed 's/Go Build.*$//'                                                                                                    ~/src/wgtunnel
build-darwin-amd64/tunnel:   Mach-O 64-bit executable x86_64
build-darwin-amd64/tunneld:  Mach-O 64-bit executable x86_64
build-darwin-arm64/tunnel:   Mach-O 64-bit executable arm64
build-darwin-arm64/tunneld:  Mach-O 64-bit executable arm64
build-linux-amd64/tunnel:    ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, 
build-linux-amd64/tunneld:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, 
build-linux-arm64/tunnel:    ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, 
build-linux-arm64/tunneld:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, 
build-linux-armv7/tunnel:    ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, 
build-linux-armv7/tunneld:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, 
build-window-amd64/tunnel:   PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
build-window-amd64/tunneld:  PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
build-windows-arm64/tunnel:  PE32+ executable (console) Aarch64 (stripped to external PDB), for MS Windows
build-windows-arm64/tunneld: PE32+ executable (console) Aarch64 (stripped to external PDB), for MS Windows
```

These binaries can be added to the release via the normal processes for wgtunnel.

Maybe add a matrix to generate binaries and upload the artefacts here?: https://github.com/coder/wgtunnel/blob/main/.github/workflows/release.yaml#L82-L100

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

I went ahead and made an example release manually, but I think we might be able to update the  release workflow to automate it.

**Comment by hh** [comment]
Note we could update the Makefile targets to include `GOOS`/`GOARCH` creating binaries in different locations, then make them all in one step:
https://github.com/coder/coder/blob/main/.github/workflows/release.yaml#L141-L152

**Comment by hh** [comment]
Manual example:
https://github.com/cloudnative-coop/wgtunnel/releases/tag/v0.1.0

**Comment by hh** [comment]
We can lower then priority on this one for now. But we should be able to update our iimatey to point to these release artifacts.

**Comment by hh** [comment]
It's fine to just use then one `ii/matey` repo for this and update the install scripts there to not need GO.

The install script should eventually use the wgtunnel artifacts generated from `coder/wgtunnel` when it merges.

But for now we are generating them in `cloudnative-coop/wgtunnel` hopefully creating a GitHub action release process that can be merged upstream.

**Comment by hh** [comment]
I think we can create a release process that sets the WIREGAURD_URL or similar default in the binary for wgtunnel via variables at the repo level, so forks can build releases with custom tunnels server locations.

**Comment by hh** [comment]
Lower priority
